# Generated by Django 4.2.5 on 2023-10-09 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_gym_membership_user_health'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gym_membership',
        ),
        migrations.RemoveField(
            model_name='user',
            name='health',
        ),
    ]
