# Generated by Django 4.2.5 on 2023-10-10 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_gym_membership_user_health'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='health',
            new_name='fitness',
        ),
    ]
