# Generated by Django 4.2.5 on 2023-10-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_payment_card_no_payment_cvv_payment_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cvv',
            field=models.IntegerField(max_length=18, null=True),
        ),
    ]
