# Generated by Django 4.2.5 on 2023-10-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gym_membership',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='health',
            field=models.BooleanField(default=False),
        ),
    ]
