# Generated by Django 4.2.5 on 2023-10-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_gym_membership_remove_user_health'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gym_membership',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='health',
            field=models.BooleanField(default=False),
        ),
    ]
