# Generated by Django 4.2.5 on 2023-10-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymMembership', '0002_rename_deitplan_dietplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excecise',
            name='videos',
            field=models.FileField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
