# Generated by Django 4.2.5 on 2023-10-31 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymMembership', '0006_dietplan_body_mass_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
