# Generated by Django 4.2.5 on 2023-10-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeitPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(choices=[('lean', 'Lean'), ('muscle', 'Muscle Building'), ('weight_loss', 'Weight Loss'), ('balanced', 'Balanced')], max_length=100)),
                ('morningPlan', models.TextField()),
                ('morningPlanImage', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('afternoonPlan', models.TextField()),
                ('afternoonPlanImage', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('nightPlan', models.TextField()),
                ('nightPlanImage', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Excecise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videos', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('images', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('images1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('images2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('images3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('images4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
