# Generated by Django 4.2.5 on 2023-10-08 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymMembership', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeitPlan',
            new_name='DietPlan',
        ),
    ]
