# Generated by Django 4.2.5 on 2023-10-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymMembership', '0003_alter_excecise_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietplan',
            name='afternoonPlanImage',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='morningPlanImage',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='nightPlanImage',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='excecise',
            name='images',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='excecise',
            name='images1',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='excecise',
            name='images2',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='excecise',
            name='images3',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='excecise',
            name='images4',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='excecise',
            name='videos',
            field=models.URLField(blank=True),
        ),
    ]
