# Generated by Django 4.2.5 on 2023-10-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymMembership', '0004_alter_dietplan_afternoonplanimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excecise',
            name='videos',
            field=models.FileField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
