# Generated by Django 4.2.5 on 2023-10-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='subscription',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly Subscription'), ('yearly', 'Yearly Subscription')], max_length=100),
        ),
    ]
