# Generated by Django 4.2.5 on 2023-10-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='card_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='cvv',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='expiry_date',
            field=models.IntegerField(null=True),
        ),
    ]
