# Generated by Django 4.2.5 on 2023-10-16 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='healine',
            new_name='headline',
        ),
    ]
