# Generated by Django 4.2.5 on 2023-11-05 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0015_orderhistory_city_orderhistory_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_address_pincode',
        ),
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
    ]
