# Generated by Django 4.2.5 on 2023-11-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0018_remove_orderhistory_city_remove_orderhistory_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='delivery_address_pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
