# Generated by Django 4.2.5 on 2023-11-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0019_orderhistory_city_orderhistory_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
