# Generated by Django 4.2.5 on 2023-11-06 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0020_alter_payment_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='city',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='country',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='delivery_address_pincode',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='state',
        ),
    ]
