# Generated by Django 4.2.5 on 2023-11-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0022_remove_order_product_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='product',
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='product',
            field=models.ManyToManyField(to='ecommerce.product'),
        ),
    ]
